preserve_hierarchy: true

files:
  - source: 'res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
languages_mapping: &anchor
      android_code:
        af: af
        am: am
        ar: ar
        as: as
        ast: ast
        az: az
        be: be
        bg: bg
        bn: bn
        bs: bs
        ca: ca
        cs: cs
        cy: cy
        da: da
        de: de
        el: el
        en-AU: en-rAU
        en-GB: en-rGB
        en-IN: en-rIN
        en-PT: en-rPT
        eo: eo
        es-ES: es
        es-MX: es-rMX
        es-US: es-rUS
        et: et
        eu: eu
        fa: fa
        fi: fi
        fr: fr
        fr-CA: fr
        fy-NL: fy
        gl: gl
        gu-IN: gu
        he: iw
        hi: hi
        hr: hr
        hu: hu
        hy-AM: hy
        id: in
        is: is
        it: it
        ja: ja
        ka: ka
        kk: kk
        km: km
        kn: kn
        ko: ko
        ku: ku
        ky: ky
        lb: lb
        lo: lo
        lt: lt
        lv: lv
        mk: mk
        ml-IN: ml
        mn: mn
        mr: mr
        ms: ms
        my: my
        nb: nb
        ne-NP: ne-rNP
        nl: nl
        or: or-rIN
        pa-IN: pa-rIN
        pl: pl
        pt-PT: pt-rPT
        pt-BR: pt-rBR
        rm-CH: rm
        ro: ro
        ru: ru
        si-LK: si-rLK
        sk: sk
        sl: sl
        sq: sq-rAL
        sr: sr
        sv-SE: sv
        sw: sw
        ta: ta
        te: te
        th: th
        tl: tl
        tr: tr
        ug: ug
        uk: uk
        ur-PK: ur
        uz: uz
        vi: vi
        zh-CN: zh-rCN
        zh-HK: zh-rHK
        zh-TW: zh-rTW
        zu: zu
